# SOME DESCRIPTIVE TITLE.
# Copyright (C) YEAR THE PACKAGE'S COPYRIGHT HOLDER
# This file is distributed under the same license as the PACKAGE package.
# FIRST AUTHOR <EMAIL@ADDRESS>, YEAR.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: PACKAGE VERSION\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2025-02-20 17:11-0300\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"Language: \n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"

#: manage_translations.py:117
#, fuzzy
msgid "Error executing command"
msgstr "Error al agregar cambios"

#: manage_translations.py:129
msgid "Choose a language"
msgstr "Elige un idioma"

#: manage_translations.py:155
msgid "Adding language"
msgstr "Agregando idioma"

#: manage_translations.py:164
msgid "Language already exists"
msgstr "El idioma ya existe"

#: manage_translations.py:175 manage_translations.py:207
msgid "No Python files found for extraction"
msgstr "No se encontraron archivos de Python para la extracción"

#: manage_translations.py:192
msgid "Language added successfully!"
msgstr "¡Idioma agregado con éxito!"

#: manage_translations.py:196
msgid "Updating translations..."
msgstr "Actualizando traducciones..."

#: manage_translations.py:201
msgid "Python files found:"
msgstr "Archivos de Python encontrados:"

#: manage_translations.py:212
msgid "Extracting strings to .pot file..."
msgstr "Extrayendo cadenas al archivo .pot..."

#: manage_translations.py:218
msgid "Updating existing translations..."
msgstr "Actualizando traducciones existentes..."

#: manage_translations.py:225
msgid "File not found:"
msgstr "Archivo no encontrado:"

#: manage_translations.py:226
msgid "Creating a new"
msgstr "Creando un nuevo"

#: manage_translations.py:231
msgid "Compiling .mo file..."
msgstr "Compilando archivo .mo..."

#: manage_translations.py:248
msgid "Translations updated successfully!"
msgstr "¡Traducciones actualizadas con éxito!"

#: manage_translations.py:261
msgid "Invalid command"
msgstr "Comando inválido"

#: manage_translations.py:265
msgid "No arguments provided"
msgstr "No se proporcionaron argumentos"

#: task_commit/init.py:61
msgid "❌ .git/hooks directory not found. Please run inside a Git repository."
msgstr ""
"❌ Directorio .git/hooks no encontrado. Por favor, ejecuta dentro de un "
"repositorio Git."

#: task_commit/init.py:71
msgid "✅ Commit-msg hook successfully configured!"
msgstr "✅ ¡Hook de commit-msg configurado con éxito!"

#: task_commit/core.py:24
msgid "y"
msgstr "s"

#: task_commit/core.py:25
msgid "n"
msgstr "n"

#: task_commit/core.py:27
msgid "Starting commit process"
msgstr "Iniciando proceso de commit"

#: task_commit/core.py:37
msgid "No changes to commit"
msgstr "No hay cambios para confirmar"

#: task_commit/core.py:44
msgid "Do you want to add all changes"
msgstr "¿Quieres agregar todos los cambios?"

#: task_commit/core.py:63
msgid "Manually add the changes and run the command again"
msgstr "Agrega los cambios manualmente y ejecuta el comando nuevamente"

#: task_commit/core.py:73 task_commit/core.py:200 task_commit/core.py:245
msgid "Invalid option"
msgstr "Opción inválida"

#: task_commit/core.py:92
msgid "Choose commit type"
msgstr "Elige el tipo de commit"

#: task_commit/core.py:111
msgid "Invalid commit type"
msgstr "Tipo de commit inválido"

#: task_commit/core.py:116
msgid "Process interrupted. Exiting..."
msgstr "Proceso interrumpido. Saliendo..."

#: task_commit/core.py:121
msgid "Unexpected error occurred"
msgstr "Ocurrió un error inesperado"

#: task_commit/core.py:130
msgid "Which module was changed? (example: core, api, models): "
msgstr "¿Qué módulo fue cambiado? (ejemplo: core, api, models): "

#: task_commit/core.py:145
msgid "Module is mandatory"
msgstr "El módulo es obligatorio"

#: task_commit/core.py:153
msgid "Enter commit message"
msgstr "Ingresa el mensaje del commit"

#: task_commit/core.py:160
msgid "Commit message is mandatory"
msgstr "El mensaje del commit es obligatorio"

#: task_commit/core.py:171
msgid "Error: Git username not set"
msgstr "Error: Nombre de usuario de Git no configurado"

#: task_commit/core.py:180
msgid "Do you want to send the commit"
msgstr "¿Quieres enviar el commit?"

#: task_commit/core.py:207
msgid "Commit canceled"
msgstr "Commit cancelado"

#: task_commit/core.py:211
msgid "Do you want to push to the repository"
msgstr "¿Quieres hacer push al repositorio?"

#: task_commit/core.py:241
msgid "Push canceled"
msgstr "Push cancelado"

#: task_commit/core.py:252
msgid "Leaving..."
msgstr "Saliendo..."

#: task_commit/core.py:257
msgid "Unexpected error"
msgstr "Error inesperado"

#: task_commit/utils.py:77
msgid "Git user is required"
msgstr "Se requiere un usuario de Git"

#: task_commit/utils.py:85
msgid "Error getting user from Git"
msgstr "Error al obtener el usuario de Git"

#: task_commit/utils.py:105 task_commit/utils.py:162
msgid "Error checking Git status"
msgstr "Error al verificar el estado de Git"

#: task_commit/utils.py:144
msgid "Changes not staged"
msgstr "Cambios no preparados"

#: task_commit/utils.py:149
msgid "Changes staged"
msgstr "Cambios preparados"

#: task_commit/utils.py:154
msgid "Untracked files"
msgstr "Archivos sin seguimiento"

#: task_commit/utils.py:179
msgid "Gitflow not installed, but push is successful"
msgstr "Gitflow no está instalado, pero el push fue exitoso"

#: task_commit/utils.py:202
msgid "Error getting current branch"
msgstr "Error al obtener la rama actual"

#: task_commit/utils.py:218
msgid "All changes added"
msgstr "Todos los cambios agregados"

#: task_commit/utils.py:221
msgid "Error adding changes"
msgstr "Error al agregar cambios"

#: task_commit/utils.py:256
msgid "Commit successful"
msgstr "Commit exitoso"

#: task_commit/utils.py:259
msgid "Error committing"
msgstr "Error al realizar el commit"

#: task_commit/utils.py:283
msgid "Do you want to 'publish' or 'finish' this branch?"
msgstr "¿Quieres 'publicar' o 'finalizar' esta rama?"

#: task_commit/utils.py:301
msgid "Error publishing branch"
msgstr "Error al publicar la rama"

#: task_commit/utils.py:309
msgid "Error finalizing branch"
msgstr "Error al finalizar la rama"

#: task_commit/utils.py:312
msgid "Invalid action"
msgstr "Acción inválida"

#: task_commit/utils.py:332
msgid "Error when pushing"
msgstr "Error al hacer push"
